name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
 
        - name: Run commands
          run: | 
           echo "My first Github Actions Job"
           ls -ltr
           cat README.md

        - name: Generate ASCII artwork using cowsay
          run: cowsay -f sparrow "This is a sparrow" >> sparrow.txt

        # - name: List files
        #   run: ls

        # - name: Read the file
        #   run: cat README.md