name: Generate ascii in multiple jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay command
          run: cowsay -f dragon "This is a dragon" >> dragon.txt

        - name: Sleep for 10 seconds
          run: sleep 10

    test_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
        - name: Sleep for 10 seconds
          run: sleep 10

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
        runs-on: ubuntu-latest
        needs: [test_job_2]
        steps:
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying.......