name: Generate ascii in multiple jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay command
          run: cowsay -f dragon "This is a dragon" >> dragon.txt

        - name: Upload the dragon file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-test-file
            path: dragon.txt

    test_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
        - name: Download the dragon file
          uses: actions/download-artifact@v4
          with:
            name: dragon-test-file

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
        runs-on: ubuntu-latest
        needs: [test_job_2]
        steps:
        - name: Download the dragon file
          uses: actions/download-artifact@v4
          with:
            name: dragon-test-file

        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying.......