name: Matrix

on: 
    push:
    workflow_dispatch:
# This job will use matrix to run parallel for all os and images. Hence this will run 4 combinations
# in parallel

jobs:
    deploy:
      strategy:
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest]
          images: [hello-world, alpine]
          exclude:
            - images: alpine, hello-world
              os: windows-latest
          include:
            - images: amd64/alpine
              os: ubuntu-20.04
      runs-on: ${{ matrix.os }}
      steps:
        - name: Echo docker details
          run: docker info

        - name: Run Images on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}