name: Setup python and go

on: push

jobs:
    setup-python:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Cli Repo
              uses: actions/checkout@v4
              with:
                repository: percona/everest
                path: cli

      #      - uses: actions/checkout@v4
            - name: Set up Go 
              uses: actions/setup-go@v5
              with:
                go-version: '1.22'
                check-latest: true
              
            - name: Check go
              run: go version

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Display Python3 version
              run: python3 -c "import sys; print(sys.version)"

            - name: List Repo Files
              run: ls -ltra $GITHUB_WORKSPACE

            - name: Check environment variable
              run: |
                echo "TOKEN=Thisisatoken" >> $GITHUB_ENV
                # Print TOKEN
                echo "TOKEN from GITHUB_ENV: $TOKEN"
                # test to check if TOKEN is available
                python3 -c "import os; print('TOKEN:', os.getenv('TOKEN'))"

       #     - name: Download cli
       #       run: |
       #         wget https://github.com/percona/everest/releases/download/v0.9.0-rc2/everestctl-linux-amd64
       #         chmod +x everestctl-linux-amd64
       #         mv everestctl-linux-amd64 everestctl
       #         ./everestctl version 

       # This works just commenting it
       #     - name: Build Cli
       #       run: |
       #         cd cli
       #         CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build-cli
       #         ./bin/everestctl version