name: Setup python and go

on: push

jobs:
    setup-python:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Cli Repo
              uses: actions/checkout@v4
              with:
                repository: percona/everest
                path: everest

      #      - uses: actions/checkout@v4
            - name: Set up Go 
              uses: actions/setup-go@v5
              with:
                go-version: '1.21'
                check-latest: true
              
            - name: Check go
              run: go version

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Display Python3 version
              run: python3 -c "import sys; print(sys.version)"

            - name: List Repo Files
              run: ls -ltra $GITHUB_WORKSPACE

       #     - name: Download cli
       #       run: |
       #         wget https://github.com/percona/everest/releases/download/v0.9.0-rc2/everestctl-linux-amd64
       #         chmod +x everestctl-linux-amd64
       #         mv everestctl-linux-amd64 everestctl
       #         ./everestctl version 

            - name: Build Cli
              run: |
                git clone https://github.com/percona/everest cli
                cd cli
                CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build-cli