name: Setup python and go

on: push

jobs:
    setup-python:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Cli Repo
              uses: actions/checkout@v4
              with:
                repository: percona/everest
                path: cli

            - uses: actions/checkout@v4
            - name: Set up Go 
              uses: actions/setup-go@v5
              with:
                go-version: '1.21'
              
            - name: Check go
              run: go version

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Display Python3 version
              run: python3 -c "import sys; print(sys.version)"

            - name: Build Cli
              run: |
                cd cli
                CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build