name: Setup python

on: push

jobs:
    setup-python:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"