name: Variables and secrets defined at repo level

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

on: push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker build
          # Use repository level variables here
          run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

        - name: Docker login
          # Use repository level secret here
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

        - name: Docker publish
          run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME}}:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
