name: Variable secrets in step

on: push
##########environment variables at STEP level##################
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker build
          env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: name1
            IMAGE_NAME: github-actions-nginx
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        
        - name: Docker login
          env:
            # We should not hard code sensitive infomation such as passwords, tokens in the workflow, 
            # this is just for demo 
            DOCKER_PASSWORD: S3cUREpaSsword!
            DOCKER_USERNAME: name1
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD


        - name: Docker publish
          env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: name1
            IMAGE_NAME: github-actions-nginx
          # Another way to use variables is to give ${{ env.variablename }} 
          run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME}}:latest
        
    deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
        - name: Docker run
          env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: name1
            IMAGE_NAME: github-actions-nginx
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
