name: Create workflow dispatch workflow

on:
    workflow_dispatch: 
      inputs:
        testtype:
          type: choice
          description: "Type of tests to run"
          options:
          - Cli
          - Api
          - UI
          required: true

jobs:
    runtests:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: .github/workflows
            
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List Repo Files
          run: ls -ltra

        - name: Check working directory
          run: pwd

        - name: Run the Cli tests
          run: echo "Running the Cli tests"
          if: ${{ github.event.inputs.testtype == 'Cli' }}

        - name: Run the APi tests
          run: echo "Set up and run the Api tests"
          if: ${{ github.event.inputs.testtype == 'Api' }}
          
        - name: Run the UI tests
          run: echo "Install setup and run the UI tests"
          if: ${{ github.event.inputs.testtype == 'UI' }}

            