name: Create workflow_dispatch workflow

on:
    workflow_dispatch: 
      inputs:
        testtype:
          description: "Type of tests to run"
          type: choice
          - Cli
          - Api
          - UI
          required: true

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
        - name: Run the tests
          run: echo "Running the test: ${{ github.event.inputs.testtype }}"
          

            