name: Create workflow dispatch workflow

on:
    workflow_dispatch: 
      inputs:
        testtype:
          type: choice
          description: "Type of tests to run"
          options:
          - Cli
          - Api
          - UI
          required: true

jobs:
    runtests:
        runs-on: ubuntu-latest
        steps:
        - name: Run the tests
          run: ls -ltr
          

            