name: Create workflow dispatch workflow

on:
    workflow_dispatch: 
      inputs:
        testtype:
          type: choice
          description: "Type of tests to run"
          options:
          - Cli
          - Api
          - UI
          required: true
        software_version:
          type: string
          description: "Software version"
          default: ''
          required: false


jobs:
    runtests:
        runs-on: ubuntu-latest
            
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List Repo Files
          run: | 
            ls -ltra
            cd testdir1
            ls -ltra

        - name: Check working directory
          run: pwd

        - name: List Repo Files of .github/workflows
          run: ls -ltra
          working-directory: .github/workflows
        
        - name: Check if install is for release or rc version
          if: ${{ github.event.inputs.software_version }}
          shell: bash
          run: |
            if [[ ${{ github.event.inputs.software_version == *{rc}* ]]; then
               echo "This is a RC version"
            else
               echo "This is a Release version"
            fi

        - name: Run the Cli tests
          run: echo "Running the Cli tests"
          if: ${{ github.event.inputs.testtype == 'Cli' }}

        - name: Run the APi tests
          run: echo "Set up and run the Api tests"
          if: ${{ github.event.inputs.testtype == 'Api' }}
          
        - name: Run the UI tests
          run: echo "Install setup and run the UI tests"
          if: ${{ github.event.inputs.testtype == 'UI' }}

            